version: "3.7"

services:
  postgres:
    image: postgres:13
    container_name: task_manager_pg
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  app:
    build: .
    container_name: task_manager
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_ADDRESS=postgres
      - DB_PORT=5432

